name: PR_Code_Review
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
jobs:
  PR_Code_Review:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runner-config: [2vcpu]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Get branch name
        id: branch_name
        run: |
          branch_name=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                        "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}" \
                        | jq -r '.head.ref')
          echo "::set-output name=diff_branch::$branch_name"
          
      - name: Get Diff Files
        id: diff_files
        run: |
          git fetch
          FILES=$(git diff ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }})
          echo $FILES >> diff_files.txt
          echo "::set-output name=diffs::$(cat diff_files.txt)"

      - name: Get Committed Files
        id: committed_files
        run: |
          git fetch --unshallow
          FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }})
          echo $FILES >> committed_files.txt
          echo "::set-output name=files::$(cat committed_files.txt)"

      - name: AI Code Review
        id: PR_Code_Review
        uses: Plative/PR_Code_Review@main
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          ghurl: ${{ github.repository }}
          anthropic_key: ${{ secrets.ANTHROPIC_API_KEY }}
          diff_code: ${{steps.committed_files.outputs.files}}
          diff_branch: ${{steps.branch_name.outputs.diff_branch}}
          diff_file: ${{steps.diff_files.outputs.diffs}}

      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `${{steps.PR_Code_Review.outputs.ai_pr_review}}`
            })
